---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[n1nj4net-dns::default]
    attributes:
  - name: server
    run_list:
      - recipe[n1nj4net-dns::server]
    attributes:
