name 'n1nj4net-dns'
maintainer 'Dayne Broderson'
maintainer_email 'broderson@gmail.com'
license 'MIT'
description 'Installs/Configures n1nj4net-dns'
long_description 'Installs/Configures n1nj4net-dns'
version '0.1.0'
